config/routes.rb
Rails.application.routes.draw do  
  root 'home#index'
  match "/404", :to => "error#not_found", :via => :all
  match "/500", :to => "error#not_found", :via => :all
  
  get "home_hot_products" => "home#hot_products", as: :home_hot_products
  get "home_stock_inventory" => "home#stock_inventory", as: :home_stock_inventory
  get "home_promotion_banner" => "home#promotion_banner", as: :home_promotion_banner
  get "home_bestselling" => "home#bestselling", as: :home_bestselling
  get "home_listing_brand" => "home#listing_brand", as: :home_listing_brand
  
  get "tim-kiem-san-pham.html" => "product_search#index", as: :product_search
  get "san-pham(/:title)-:id.html" => "product#index", as: :product
  get "chuyen-muc(/:title)-:id.html" => "category_page#index", as: :category
  get "hinh-anh(/:title)(/:id)/(:type)" => "product_images#image", as: :product_image
  get "xem-nhanh.html" => "product#quickview", as: :product_quickview

  get "tin-tuc.html" => "blog#index", as: :blog_listing
  get "tin-tuc(/:title)-:id.html" => "blog#detail", as: :blog_detail  
  get "gioi-thieu.html" => "about_us#index", as: :about_us
  get "lien-he.html" => "contact#index", as: :contact
  get "lien-he/gui-loi-nhan-thanh-cong.html" => "contact#finish_contact", as: :finish_contact

  get "gio-hang.html" => "shopping_cart#index", as: :shopping_cart
  get "dat-hang.html" => "check_out#index", as: :check_out
  get "dat-hang/thanh-cong.html" => "finish_checkout#index", as: :finish_checkout

  get "huong-dan-mua-hang.html" => "information#policy_1", as: :policy_1
  get "huong-dan-thanh-toan.html" => "information#policy_2", as: :policy_2
  get "chinh-sach-van-chuyen-giao-nhan.html" => "information#policy_3", as: :policy_3
  get "chinh-sach-bao-hanh.html" => "information#policy_4", as: :policy_4
  get "chinh-sach-doi-tra-hang-va-hoan-tien.html" => "information#policy_5", as: :policy_5
  get "quy-dinh-bao-mat-thong-tin.html" => "information#policy_6", as: :policy_6
  get "quy-che-hoat-dong-trang-tmdt.html" => "information#policy_7", as: :policy_7
  get "cac-dieu-khoan-va-dieu-kien.html" => "information#policy_8", as: :policy_8
  get "cau-hoi-thuong-gap.html" => "information#policy_9", as: :policy_9

	get "autosearch" => "product#autosearch", as: :autosearch

  devise_for :logins
  resources :customer_orders
  resources :line_items
  resources :carts
  resources :category
  resources :product

  namespace :admin, :path => "hoangkhangincotech" do
      resources :partners
      resources :articles
      resources :tags
      resources :slide_shows
      resources :newsletters
      resources :messages
      resources :manages
      resources :menus
      resources :customer_orders
      resources :product_infos
      get "old_category" => "old_category#index", as: :old_category
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @menus = Menu.get_menus    
  end

  def hot_products
    render layout: nil
  end

  def stock_inventory
    render layout: nil
  end

  def promotion_banner
    render layout: nil
  end

  def bestselling
    render layout: nil
  end

  def listing_brand
    render layout: nil
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_not_using_ajax.html.erb
<div class="block-section-4">
    <div class="container">
        <div class="title-of-section">SẢN PHẨM NỔI BẬT</div>
        <div class="tab-product tab-product-fade-effect">
            <%= render '/modules/home/hot_products', menus: @menus %>
        </div>
    </div>
</div>
<div class="block-section-5">
  <div class="full-width background-section-5">
       <div class="container">
           <div class="title-of-section style2">XẢ KHO HÀNG TỒN</div>
           <div class="tab-product tab-product-fade-effect">
               <%= render '/modules/home/stock_inventory' %>
           </div>
       </div>
  </div>
</div>
<div class="block-section-6">
    <div class="container">
        <%= render '/modules/home/promotion_banner' %>
    </div>
</div>
<div class="block-recent-view">
    <div class="container">
        <div class="title-of-section">SẢN PHẨM BÁN CHẠY</div>
        <%= render '/modules/bestselling' %>
    </div>
</div>
<div class="block-section-brand">
    <div class="container">
        <div class="title-of-section">THƯƠNG HIỆU SẢN PHẨM</div>
        <%= render '/modules/listing_brand' %>
    </div>
</div>

app/views/home/_using_ajax.html.erb
<div class="ajax-box" data-url="<%= home_hot_products_path %>"></div>
<div class="ajax-box" data-url="<%= home_stock_inventory_path %>"></div>
<div class="ajax-box" data-url="<%= home_promotion_banner_path %>"></div>
<div class="ajax-box" data-url="<%= home_bestselling_path %>"></div>
<div class="ajax-box" data-url="<%= home_listing_brand_path %>"></div>

app/views/home/bestselling.html.erb
<div class="block-recent-view">
    <div class="container">
        <div class="title-of-section">Sản Phẩm Bán Chạy</div>
        <%= render '/modules/bestselling' %>
    </div>
</div>

<%= javascript_include_tag '/hksite/js/function.js' %>

app/views/home/hot_products.html.erb
<div class="block-section-4">
    <div class="container">
        <div class="title-of-section">SẢN PHẨM NỔI BẬT</div>
        <div class="tab-product tab-product-fade-effect">
            <%= render '/modules/home/hot_products' %>
        </div>
    </div>
</div>

<%= javascript_include_tag '/hksite/js/function.js' %>

app/views/home/index.html.erb
<main class="site-main">
    <%= render '/modules/home/newsletter_popup' %>
    <div class="block-section-1">
        <%= render '/modules/home/slider' %>
    </div>
    <% if Product.get_sale_products.count > 0 %>
    <div class="block-daily-deals style1">
        <div class="container">
            <div class="title-of-section">SẢN PHẨM GIẢM GIÁ</div>
            <%= render '/modules/home/daily_deals' %>
        </div>
    </div>
    <!--<div class="block-section-3">
        <div class="container">
            <%= render '/modules/home/deal_banners' %>
        </div>
    </div>-->
    <% end %>
    <%= render '/home/not_using_ajax' %>
</main>

app/views/home/listing_brand.html.erb
<div class="block-section-brand">
    <div class="container">
        <div class="title-of-section">THƯƠNG HIỆU SẢN PHẨM</div>
        <%= render '/modules/listing_brand' %>
    </div>
</div>

<%= javascript_include_tag '/hksite/js/function.js' %>

app/views/home/promotion_banner.html.erb
<div class="block-section-6">
    <div class="container">
        <%= render '/modules/home/promotion_banner' %>
    </div>
</div>

<%= javascript_include_tag '/hksite/js/function.js' %>

app/views/home/stock_inventory.html.erb
<div class="block-section-5">
  <div class="full-width background-section-5">
       <div class="container">
           <div class="title-of-section style2">XẢ KHO HÀNG TỒN</div>
           <div class="tab-product tab-product-fade-effect">
               <%= render '/modules/home/stock_inventory' %>
           </div>
       </div>
  </div>
</div>

<%= javascript_include_tag '/hksite/js/function.js' %>