config/routes.rb
Rails.application.routes.draw do  
  root 'home#index'
  match "/404", :to => "error#not_found", :via => :all
  match "/500", :to => "error#not_found", :via => :all
  
  get "home_hot_products" => "home#hot_products", as: :home_hot_products
  get "home_stock_inventory" => "home#stock_inventory", as: :home_stock_inventory
  get "home_promotion_banner" => "home#promotion_banner", as: :home_promotion_banner
  get "home_bestselling" => "home#bestselling", as: :home_bestselling
  get "home_listing_brand" => "home#listing_brand", as: :home_listing_brand
  
  get "tim-kiem-san-pham.html" => "product_search#index", as: :product_search
  get "san-pham(/:title)-:id.html" => "product#index", as: :product
  get "chuyen-muc(/:title)-:id.html" => "category_page#index", as: :category
  get "hinh-anh(/:title)(/:id)/(:type)" => "product_images#image", as: :product_image
  get "xem-nhanh.html" => "product#quickview", as: :product_quickview

  get "tin-tuc.html" => "blog#index", as: :blog_listing
  get "tin-tuc(/:title)-:id.html" => "blog#detail", as: :blog_detail  
  get "gioi-thieu.html" => "about_us#index", as: :about_us
  get "lien-he.html" => "contact#index", as: :contact
  get "lien-he/gui-loi-nhan-thanh-cong.html" => "contact#finish_contact", as: :finish_contact

  get "gio-hang.html" => "shopping_cart#index", as: :shopping_cart
  get "dat-hang.html" => "check_out#index", as: :check_out
  get "dat-hang/thanh-cong.html" => "finish_checkout#index", as: :finish_checkout

  get "huong-dan-mua-hang.html" => "information#policy_1", as: :policy_1
  get "huong-dan-thanh-toan.html" => "information#policy_2", as: :policy_2
  get "chinh-sach-van-chuyen-giao-nhan.html" => "information#policy_3", as: :policy_3
  get "chinh-sach-bao-hanh.html" => "information#policy_4", as: :policy_4
  get "chinh-sach-doi-tra-hang-va-hoan-tien.html" => "information#policy_5", as: :policy_5
  get "quy-dinh-bao-mat-thong-tin.html" => "information#policy_6", as: :policy_6
  get "quy-che-hoat-dong-trang-tmdt.html" => "information#policy_7", as: :policy_7
  get "cac-dieu-khoan-va-dieu-kien.html" => "information#policy_8", as: :policy_8
  get "cau-hoi-thuong-gap.html" => "information#policy_9", as: :policy_9

	get "autosearch" => "product#autosearch", as: :autosearch

  devise_for :logins
  resources :customer_orders
  resources :line_items
  resources :carts
  resources :category
  resources :product

  namespace :admin, :path => "hoangkhangincotech" do
      resources :partners
      resources :articles
      resources :tags
      resources :slide_shows
      resources :newsletters
      resources :messages
      resources :manages
      resources :menus
      resources :customer_orders
      resources :product_infos
      get "old_category" => "old_category#index", as: :old_category
  end
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, dependent: :destroy
  
  def add_product(product_id)
    current_item = line_items.find_by(product_id: product_id)
    if current_item
        current_item.quantity += 1
    else
        current_item = line_items.build(product_id: product_id)
    end
    current_item
  end
  
  def count_quantity
    line_items.sum(:quantity)
  end
  
  def remove_item(line_item_id)
    self.line_items.where(id: line_item_id).destroy_all
  end
  
  def total_order
    amount = 0.0
    self.line_items.each do |od|
      amount += od.total_item
    end
    return amount
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all.order("created_at DESC")
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    params[:quantities].each do |q|
      li = LineItem.find(q[0])
      li.update_attribute(:quantity, q[1])
    end
    
    redirect_to shopping_cart_path, notice: 'update-success'
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to shopping_cart_path, notice: 'delete-success' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params[:cart]
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<!-- Main content -->
<div class="content-wrapper">

    <!-- Page header -->
    <div class="page-header">
        <div class="page-header-content">
            <div class="page-title">
                <h4><a href="#" class="btn-back"><i class="icon-arrow-left52 position-left"></i></a> <span class="text-semibold">Danh sách</span> - Đơn hàng</h4>
            </div>
        </div>
    
        <div class="breadcrumb-line">
            <ul class="breadcrumb">
                <li><%= link_to '<i class="icon-home2 position-left"></i> Trang chủ'.html_safe, admin_manages_path %></li>
                <li><%= link_to 'Quản lý đơn hàng', admin_tags_path %></li>
                <li class="active">Danh sách đơn hàng</li>
            </ul>
        </div>
    </div>
    <!-- /page header -->
    
    
    <!-- Content area -->
    <div class="content">
    
        <!-- Basic TableTools example -->
        <div class="panel panel-flat">
            <div class="panel-heading">
                <h5 class="panel-title">Danh sách <span class="text-semibold">đơn hàng</span></h5>
                <div class="heading-elements">
                    <ul class="icons-list">
                        <li><a data-action="collapse"></a></li>
                        <li><a data-action="reload"></a></li>
                        <li><a data-action="close"></a></li>
                    </ul>
                </div>
            </div>	
    
            <table class="table datatable-order">
                <thead>
                    <tr>
                        <th>Hình ảnh</th>
                        <th>Tên sản phẩm</th>
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
        </div>
        <!-- /basic TableTools example -->
    
        <!-- Footer -->
        <%= render '/admin/manages/footer' %>
        <!-- /footer -->
    
    </div>
    <!-- /content area -->

</div>
<!-- /main content -->

<!-- Theme JS files -->
<%= javascript_include_tag '/backend/assets/js/plugins/tables/datatables/datatables.min.js' %>
<%= javascript_include_tag '/backend/javascripts/tools.min.product.js' %>
<%= javascript_include_tag '/backend/assets/js/plugins/forms/selects/select2.min.js' %>

<%= javascript_include_tag '/backend/assets/js/core/app.js' %>
<%= javascript_include_tag '/backend/javascripts/datatables_order.js' %>
<!-- /theme JS files -->

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_cart_path(@cart) %> |
<%= link_to 'Back', carts_path %>