config/routes.rb
Rails.application.routes.draw do  
  root 'home#index'
  match "/404", :to => "error#not_found", :via => :all
  match "/500", :to => "error#not_found", :via => :all
  
  get "home_hot_products" => "home#hot_products", as: :home_hot_products
  get "home_stock_inventory" => "home#stock_inventory", as: :home_stock_inventory
  get "home_promotion_banner" => "home#promotion_banner", as: :home_promotion_banner
  get "home_bestselling" => "home#bestselling", as: :home_bestselling
  get "home_listing_brand" => "home#listing_brand", as: :home_listing_brand
  
  get "tim-kiem-san-pham.html" => "product_search#index", as: :product_search
  get "san-pham(/:title)-:id.html" => "product#index", as: :product
  get "chuyen-muc(/:title)-:id.html" => "category_page#index", as: :category
  get "hinh-anh(/:title)(/:id)/(:type)" => "product_images#image", as: :product_image
  get "xem-nhanh.html" => "product#quickview", as: :product_quickview

  get "tin-tuc.html" => "blog#index", as: :blog_listing
  get "tin-tuc(/:title)-:id.html" => "blog#detail", as: :blog_detail  
  get "gioi-thieu.html" => "about_us#index", as: :about_us
  get "lien-he.html" => "contact#index", as: :contact
  get "lien-he/gui-loi-nhan-thanh-cong.html" => "contact#finish_contact", as: :finish_contact

  get "gio-hang.html" => "shopping_cart#index", as: :shopping_cart
  get "dat-hang.html" => "check_out#index", as: :check_out
  get "dat-hang/thanh-cong.html" => "finish_checkout#index", as: :finish_checkout

  get "huong-dan-mua-hang.html" => "information#policy_1", as: :policy_1
  get "huong-dan-thanh-toan.html" => "information#policy_2", as: :policy_2
  get "chinh-sach-van-chuyen-giao-nhan.html" => "information#policy_3", as: :policy_3
  get "chinh-sach-bao-hanh.html" => "information#policy_4", as: :policy_4
  get "chinh-sach-doi-tra-hang-va-hoan-tien.html" => "information#policy_5", as: :policy_5
  get "quy-dinh-bao-mat-thong-tin.html" => "information#policy_6", as: :policy_6
  get "quy-che-hoat-dong-trang-tmdt.html" => "information#policy_7", as: :policy_7
  get "cac-dieu-khoan-va-dieu-kien.html" => "information#policy_8", as: :policy_8
  get "cau-hoi-thuong-gap.html" => "information#policy_9", as: :policy_9

	get "autosearch" => "product#autosearch", as: :autosearch

  devise_for :logins
  resources :customer_orders
  resources :line_items
  resources :carts
  resources :category
  resources :product

  namespace :admin, :path => "hoangkhangincotech" do
      resources :partners
      resources :articles
      resources :tags
      resources :slide_shows
      resources :newsletters
      resources :messages
      resources :manages
      resources :menus
      resources :customer_orders
      resources :product_infos
      get "old_category" => "old_category#index", as: :old_category
  end
end

app/models/newsletter.rb
class Newsletter < ActiveRecord::Base
end

app/controllers/admin/newsletters_controller.rb
class Admin::NewslettersController < ApplicationController
  before_action :set_newsletter, only: [:show, :edit, :update, :destroy]

  # GET /newsletters
  # GET /newsletters.json
  def index
    @newsletters = Newsletter.all.order("created_at DESC")
  end

  # GET /newsletters/1
  # GET /newsletters/1.json
  def show
  end

  # GET /newsletters/new
  def new
    @newsletter = Newsletter.new
  end

  # GET /newsletters/1/edit
  def edit
  end

  # POST /newsletters
  # POST /newsletters.json
  def create
    @newsletter = Newsletter.new(newsletter_params)

    respond_to do |format|
      if @newsletter.save
        format.html { redirect_to root_path, notice: 'Cảm ơn quý khách đã đăng ký nhận tin.' }
        format.json { render :show, status: :created, location: @newsletter }
      else
        format.html { render :new }
        format.json { render json: @newsletter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /newsletters/1
  # PATCH/PUT /newsletters/1.json
  def update
    respond_to do |format|
      if @newsletter.update(newsletter_params)
        format.html { redirect_to [:admin, @newsletter], notice: 'Newsletter was successfully updated.' }
        format.json { render :show, status: :ok, location: @newsletter }
      else
        format.html { render :edit }
        format.json { render json: @newsletter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /newsletters/1
  # DELETE /newsletters/1.json
  def destroy
    @newsletter.destroy
    respond_to do |format|
      format.html { redirect_to [:admin, @newsletter] }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_newsletter
      @newsletter = Newsletter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def newsletter_params
      params.require(:newsletter).permit(:email)
    end
end

app/helpers/newsletters_helper.rb
module NewslettersHelper
end

app/views/admin/newsletters/_form.html.erb
<%= form_for(@newsletter) do |f| %>
  <% if @newsletter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@newsletter.errors.count, "error") %> prohibited this newsletter from being saved:</h2>

      <ul>
      <% @newsletter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/newsletters/edit.html.erb
<h1>Editing Newsletter</h1>

<%= render 'form' %>

<%= link_to 'Show', @newsletter %> |
<%= link_to 'Back', newsletters_path %>

app/views/admin/newsletters/index.html.erb
<!-- Main content -->
<div class="content-wrapper">

    <!-- Page header -->
    <div class="page-header">
        <div class="page-header-content">
            <div class="page-title">
                <h4><span class="text-semibold">Quản lý email nhận tin mới</span></h4>
            </div>
        </div>

        <div class="breadcrumb-line">
            <ul class="breadcrumb">
                <li><%= link_to '<i class="icon-home2 position-left"></i> Trang chủ'.html_safe, admin_manages_path %></li>
                <li><%= link_to 'Quản lý trang chủ', admin_newsletters_path %></li>
                <li class="active">Quản lý email nhận tin mới</li>
            </ul>
        </div>
    </div>
    <!-- /page header -->


    <!-- Content area -->
    <div class="content">

        <!-- Basic datatable -->
        <div class="panel panel-flat">
            <div class="panel-heading">
                <h5 class="panel-title">Danh sách email</h5>
                <div class="heading-elements">
                    <ul class="icons-list">
                        <li><a data-action="collapse"></a></li>
                        <li><a data-action="reload"></a></li>
                        <li><a data-action="close"></a></li>
                    </ul>
                </div>
            </div>

            <table class="table datatable-newsletter">
                <thead>
                    <tr>
                        <th>Email</th>
                        <th>Ngày tạo</th>
                        <th class="text-center">Thao tác</th>
                    </tr>
                </thead>
                <tbody>
                    <% @newsletters.each do |item| %>
                        <tr>
                            <td><%= item.email %></td>
                            <td><%= item.created_at.strftime("%d/%m/%Y") %></td>
                            <td class="text-center">
                                <ul class="icons-list">
                                    <li class="dropdown">
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                            <i class="icon-menu9"></i>
                                        </a>
    
                                        <ul class="dropdown-menu dropdown-menu-right">
                                            <li><%= link_to '<i class="icon-cross2"></i> Xóa'.html_safe, [:admin, item], method: :delete, data: {confirm: 'Bạn có chắc muốn xóa dòng này?'} %></li>
                                        </ul>
                                    </li>
                                </ul>
                            </td>
                        </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
        <!-- /basic datatable -->

        <!-- Footer -->
        <%= render '/admin/manages/footer' %>
        <!-- /footer -->

    </div>
    <!-- /content area -->

</div>
<!-- /main content -->

<!-- Theme JS files -->
<%= javascript_include_tag '/backend/assets/js/plugins/tables/datatables/datatables.min.js' %>
<%= javascript_include_tag '/backend/assets/js/plugins/forms/selects/select2.min.js' %>

<%= javascript_include_tag '/backend/assets/js/core/app.js' %>
<%= javascript_include_tag '/backend/javascripts/datatables_newsletter.js' %>
<!-- /theme JS files -->

app/views/admin/newsletters/new.html.erb
<h1>New Newsletter</h1>

<%= render 'form' %>

<%= link_to 'Back', newsletters_path %>

app/views/admin/newsletters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @newsletter.email %>
</p>

<%= link_to 'Edit', edit_newsletter_path(@newsletter) %> |
<%= link_to 'Back', newsletters_path %>